version: "3"
services:
  app:
    container_name: express-mongo
    image: ftperez11/reviews-sdc_app:latest
    restart: always
    # build: ./
    # command: bash -c 'npm start'
    ports:
      - "80:5001"
    # volumes:
    #   - .:/app
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"